version: '3'
services:
  chisel:
    image: jakub300/chisel
    volumes:
      - .:/home/chisel/project
    links:
      - db
      - chisel-webserver:chisel-project
    ports:
      - ${CHISEL_DEV_PORT-3000}:3000
  chisel-webserver:
    image: jakub300/chisel-webserver
    volumes:
      - ./wp:/var/www/html/
    links:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./docker-database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
