# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

jobs:
  build-v6: &defaults
    docker:
      - image: circleci/node:6
      - image: circleci/mysql
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v3-dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run: sudo apt-get update && sudo apt-get install -y php5-cli php5-mysql mysql-client
      - run:
          name: Install dependencies required by Chrome Headless
          command: >
            sudo apt-get install gconf-service libasound2 libatk1.0-0 libcups2
            libdbus-1-3 libgconf-2-4 libgtk-3-0 libnspr4 libxcomposite1
            libxcursor1 libxi6 libxrandr2 libxss1 libxtst6 fonts-liberation
            libappindicator1 libnss3 lsb-release xdg-utils wget
      - run: |
          sudo npm install -g yo
          wget -P /tmp https://github.com/wp-premium/advanced-custom-fields-pro/archive/master.zip
          wget -P /tmp https://github.com/wp-premium/gravityforms/archive/master.zip
          wget -P /tmp https://github.com/wp-sync-db/wp-sync-db/archive/master.zip
          wget -P /tmp https://github.com/wp-sync-db/wp-sync-db-media-files/archive/master.zip
      - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
            - test/generated_project/yarn.lock
            - test/generated_project/node_modules
          key: v3-dependencies-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package.json" }}
      - run: yarn test
  build-v7:
    <<: *defaults
    docker:
      - image: circleci/node:7
      - image: circleci/mysql
  build-v8:
    <<: *defaults
    docker:
      - image: circleci/node:8
      - image: circleci/mysql
  build-v9:
    <<: *defaults
    docker:
      - image: circleci/node:9
      - image: circleci/mysql

  test-versions-generator: &test-versions
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install -y php5-cli
      - run: yarn test
    environment:
      TEST_VERSIONS: generator
  test-versions-generated-project:
    <<: *test-versions
    environment:
      TEST_VERSIONS: generated_project

  pack:
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get install -y php5-cli
      - run: npm pack
      - run: mv generator-chisel-*.tgz generator-chisel.tgz
      - store_artifacts:
          path: generator-chisel.tgz
          destination: packaged/generator-chisel.tgz


workflows:
  version: 2
  build:
    jobs:
      - build-v6
      - build-v7
      - build-v8
      - build-v9
      - test-versions-generator:
          requires:
            - build-v6
            - build-v7
            - build-v8
            - build-v9
      - test-versions-generated-project:
          requires:
            - build-v6
            - build-v7
            - build-v8
            - build-v9
      - pack:
          requires:
            - test-versions-generator
            - test-versions-generated-project

