# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

jobs:
  build-v6: &defaults
    docker:
      - image: circleci/node:6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: sudo apt-get install -y php5-cli php5-mysql
      - run: env
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
  build-v8:
    <<: *defaults
    docker:
      - image: circleci/node:8
  build-v9:
    <<: *defaults
    docker:
      - image: circleci/node:9

workflows:
  version: 2
  build:
    jobs:
      - build-v6
      - build-v8
      - build-v9

